In [1]:
import pandas as pd
import numpy as np
from os import getcwd

In [2]:
pwd

'/lab/public-heath-study/data-analysis'

## Question 1
Donnez le résultat de votre calcul pour l'année 2013

In [3]:
pop=pd.read_csv("../data/fr_population.csv")
pop=pop[['Zone','Valeur','Code zone']]
pop['Valeur']=pop['Valeur']*1000
pop=pop.rename(columns={"Valeur":"population", "Zone":"pays", "Code zone":"zone"})
pop.head()

             pays  population  zone
0     Afghanistan    30552000     2
1  Afrique du Sud    52776000   202
2         Albanie     3173000     3
3         Algérie    39208000     4
4       Allemagne    82727000    79

In [4]:
pop['population'].sum()

8413993000

In [5]:
pop.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
170    False
171    False
172    False
173    False
174    False
Length: 175, dtype: bool

In [6]:
pop.drop_duplicates(subset=['pays'], keep= False)
pop=pop.loc[pop['pays']!= 'Chine',:]
pop.shape
pop['population'].sum()

6997326000

In [7]:
pop=pop.loc[pop['pays']!= 'Chine',:]

In [8]:
pop.shape

(174, 3)

In [9]:
pop['population'].sum()

6997326000

## Question 2 
Identifier les redondances

In [10]:
# Import des données des bilans alimentaires 
veg = pd.read_csv("../data/fr_vegetaux.csv")
ani = pd.read_csv("../data/fr_animaux.csv")


# Ajout de la variable origin
ani["Origine"] = "animale"
veg["Origine"] = "vegetale"


# On regroupe veg et ani en un unique dataframe, via une union
temp = ani.append(veg)


# Suppression de ani et veg
del ani, veg


# Transformation de temp en table pivot
data = temp.pivot_table(index=["Zone","Produit","Code Produit","Origine"],
                        columns = ["Élément"], values=["Valeur"], aggfunc=sum)

data.columns = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité alimentaire (Kcal/personne/jour)', 
                'Disponibilité alimentaire en quantité (kg/personne/an)', 
                'Disponibilité de matière grasse en quantité (g/personne/jour)', 
                'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 
                'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 
                'Semences', 'Traitement', 'Variation de stock']


dispo_alimentaire = data.reset_index()

#Nourriture = nouriture pour humain

dispo_alimentaire.head()

,Zone,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [11]:
listecolonne = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité intérieure', 
                'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 
                'Semences', 'Traitement', 'Variation de stock']


for colonne in listecolonne :
    dispo_alimentaire[colonne] = dispo_alimentaire[colonne] * 1000000

## Question 3 
Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

In [12]:
dispo_alimentaire=dispo_alimentaire.rename(columns={"Zone":"pays"})
dispo_alimentaire=dispo_alimentaire.merge(pop,on="pays")
dispo_alimentaire.head()
dispo_alimentaire['Dispokcal']= dispo_alimentaire ['Disponibilité alimentaire (Kcal/personne/jour)']*dispo_alimentaire['population']*365
dispo_alimentaire.head()
dispo_alimentaire['Dispoperproteine']=dispo_alimentaire ['Disponibilité de protéines en quantité (g/personne/jour)']*dispo_alimentaire['population']*365/1000
dispo_alimentaire.head()

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,population,zone,Dispokcal,Dispoperproteine
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,...,53000000.0,NaN,53000000.0,NaN,NaN,NaN,30552000,2,5.575740e+10,8586639.6
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,39000000.0,2000000.0,3000000.0,NaN,NaN,NaN,30552000,2,1.115148e+10,223029.6
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,2000000.0,NaN,NaN,NaN,NaN,NaN,30552000,2,1.115148e+10,334544.4
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,30552000,2,0.000000e+00,NaN
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,82000000.0,NaN,NaN,NaN,NaN,NaN,30552000,2,4.460592e+10,557574.0

In [13]:
dispo_alimentaire=dispo_alimentaire.merge(pop,on="pays")
dispo_alimentaire.head()

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,population_y,zone_y
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,...,53000000.0,NaN,NaN,NaN,30552000,2,5.575740e+10,8586639.6,30552000,2
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,3000000.0,NaN,NaN,NaN,30552000,2,1.115148e+10,223029.6,30552000,2
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,NaN,NaN,NaN,NaN,30552000,2,1.115148e+10,334544.4,30552000,2
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,30552000,2,0.000000e+00,NaN,30552000,2
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,NaN,NaN,NaN,NaN,30552000,2,4.460592e+10,557574.0,30552000,2

In [14]:
dispo_alimentaire['Dispokcal'] = dispo_alimentaire ['Disponibilité alimentaire (Kcal/personne/jour)']*pop['population']*365
dispo_alimentaire.head()

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,population_y,zone_y
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,...,53000000.0,NaN,NaN,NaN,30552000,2,5.575740e+10,8586639.6,30552000,2
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,3000000.0,NaN,NaN,NaN,30552000,2,1.926324e+10,223029.6,30552000,2
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,NaN,NaN,NaN,NaN,30552000,2,1.158145e+09,334544.4,30552000,2
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,30552000,2,0.000000e+00,NaN,30552000,2
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,NaN,NaN,NaN,NaN,30552000,2,1.207814e+11,557574.0,30552000,2

In [15]:
dispo_alimentaire['Dispoperproteine']=dispo_alimentaire ['Disponibilité de protéines en quantité (g/personne/jour)']*pop['population']*365/1000
dispo_alimentaire.head()

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,population_y,zone_y
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,...,53000000.0,NaN,NaN,NaN,30552000,2,5.575740e+10,8586639.60,30552000,2
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,3000000.0,NaN,NaN,NaN,30552000,2,1.926324e+10,385264.80,30552000,2
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,NaN,NaN,NaN,NaN,30552000,2,1.158145e+09,34744.35,30552000,2
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,30552000,2,0.000000e+00,NaN,30552000,2
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,NaN,NaN,NaN,NaN,30552000,2,1.207814e+11,1509767.75,30552000,2

## Question 4 
Calculez pour chaque produit le ratio energie/poids

In [16]:
dispo_alimentaire['Ratioenergiepoid']=dispo_alimentaire['Dispokcal']/ dispo_alimentaire ['Nourriture']
dispo_alimentaire['Ratioperproteine']=dispo_alimentaire['Dispoperproteine']/ dispo_alimentaire ['Nourriture']
dispo_alimentaire.head()
dispo_alimentaire = dispo_alimentaire.replace([np.inf, -np.inf],np.nan)
ratio =dispo_alimentaire.groupby ('Produit').mean()
ratio =ratio.reset_index()
ratio.head()
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Oeufs',:]
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Avoine',:]

  Produit  Ratioenergiepoid  Ratioperproteine
7  Avoine          705.7275          0.022583

In [17]:
dispo_alimentaire = dispo_alimentaire.replace([np.inf, -np.inf],np.nan)
ratio =dispo_alimentaire.groupby ('Produit').mean()
ratio =ratio.reset_index()
ratio.head()

,Produit,Code Produit,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,...,Traitement,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,population_y,zone_y,Ratioenergiepoid,Ratioperproteine
0,Abats Comestible,2736.0,4.386957e+07,1.630769e+07,8.505747,2.730345,0.254767,1.328621,1.010747e+08,3.648889e+07,...,NaN,4.814815e+05,4.021452e+07,125.431034,1.623721e+11,2.461568e+07,4.021452e+07,125.431034,1857.023287,0.276413
1,"Agrumes, Autres",2614.0,NaN,3.125000e+06,0.831169,1.348839,0.008211,0.018559,7.610000e+07,6.148148e+06,...,6000000.0,8.518519e+05,4.267466e+07,125.725000,6.421080e+09,1.284216e+05,4.267466e+07,125.725000,164.643077,0.003293
2,"Alcool, non Comestible",2659.0,NaN,1.377785e+08,NaN,NaN,NaN,NaN,1.358812e+08,7.920000e+07,...,NaN,2.065217e+07,4.212981e+07,125.693750,NaN,NaN,4.212981e+07,125.693750,NaN,NaN
3,Aliments pour enfants,2680.0,NaN,0.000000e+00,4.049689,0.404596,0.031824,0.168696,4.912281e+05,7.609023e+06,...,NaN,1.951220e+05,4.071432e+07,125.023392,1.946423e+09,7.399645e+04,4.071432e+07,125.023392,579.072500,0.017372
4,Ananas,2618.0,NaN,4.285714e+05,3.922619,3.890536,0.015200,0.031544,1.385833e+08,5.557971e+07,...,800000.0,5.132353e+06,4.082818e+07,125.702381,3.151775e+09,9.455325e+04,4.082818e+07,125.702381,219.891279,0.002199

In [18]:
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Oeufs',:]

   Produit  Ratioenergiepoid  Ratioperproteine
58   Oeufs        600.030704          0.045922

la teneur en proteine de l'avoine

In [19]:
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Avoine',:]

  Produit  Ratioenergiepoid  Ratioperproteine
7  Avoine          705.7275          0.022583

## Question 5
Citez 5 aliments parmi les 20 aliments les plus caloriques

In [20]:
ratio.sort_values (by = 'Ratioenergiepoid', ascending = False)

                    Produit  Ratioenergiepoid  Ratioperproteine
37  Huile de Colza&Moutarde      73132.130000               NaN
57                     Noix      72691.064586          2.295671
16             Cephalopodes      16731.600000          2.835458
12                      Blé      14343.435825          0.452039
92         Viande de Bovins      11394.283138          0.796969
..                      ...               ...               ...
77              Racines nda               NaN               NaN
84     Sucre non centrifugé               NaN               NaN
85         Sucre, betterave               NaN               NaN
86             Sucre, canne               NaN               NaN
91   Viande de Anim Aquatiq               NaN               NaN

[98 rows x 3 columns]

## Question 6
Calculez pour les produits végétaux la dispo interieur mondiale exprimé en kcal

In [21]:
dfvegetaux = dispo_alimentaire.loc[dispo_alimentaire['Origine'] == 'vegetale',:]
dfvegetaux.head()

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Traitement,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,population_y,zone_y,Ratioenergiepoid,Ratioperproteine
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,NaN,NaN,30552000,2,1.926324e+10,385264.80,30552000,2,493.929231,0.009879
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,NaN,NaN,30552000,2,1.158145e+09,34744.35,30552000,2,579.072500,0.017372
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,NaN,NaN,30552000,2,0.000000e+00,NaN,30552000,2,NaN,NaN
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,NaN,NaN,30552000,2,1.207814e+11,1509767.75,30552000,2,1472.944146,0.018412
6,Afghanistan,Bière,2656,vegetale,NaN,NaN,0.0,0.09,NaN,0.00,...,NaN,NaN,30552000,2,0.000000e+00,0.00,30552000,2,0.000000,0.000000

In [22]:
dfvegetaux['dispointerieurKcal'] = dfvegetaux ['Disponibilité intérieure'] * dfvegetaux ['Ratioenergiepoid']
dfvegetaux.head()

<ipython-input-22-2e1839138b87>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfvegetaux['dispointerieurKcal'] = dfvegetaux ['Disponibilité intérieure'] * dfvegetaux ['Ratioenergiepoid']

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,population_y,zone_y,Ratioenergiepoid,Ratioperproteine,dispointerieurKcal
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,NaN,30552000,2,1.926324e+10,385264.80,30552000,2,493.929231,0.009879,2.025110e+10
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,NaN,30552000,2,1.158145e+09,34744.35,30552000,2,579.072500,0.017372,1.158145e+09
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,NaN,30552000,2,0.000000e+00,NaN,30552000,2,NaN,NaN,NaN
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,NaN,30552000,2,1.207814e+11,1509767.75,30552000,2,1472.944146,0.018412,1.207814e+11
6,Afghanistan,Bière,2656,vegetale,NaN,NaN,0.0,0.09,NaN,0.00,...,NaN,30552000,2,0.000000e+00,0.00,30552000,2,0.000000,0.000000,0.000000e+00

## Question 7
Combien d'humains pourraient être nourris si toute la disponibilité intérieur mondiale de produits végétaux était utilisé pour de la nourriture

En termes de calories sachant qu'en moyenne une personne a besoin de 2500 calories par jour

In [23]:
resp1 = dfvegetaux['dispointerieurKcal'].sum()/365 / 2800
KG_PROT_PER_CAPITA_PER_DAY = 62 * .9 * .001
dfvegetaux['dispointerieurprot'] = dfvegetaux ['Disponibilité intérieure'] * dfvegetaux ['Ratioperproteine']
dfvegetaux.head()
resp2 = dfvegetaux['dispointerieurprot'].sum()/KG_PROT_PER_CAPITA_PER_DAY
resp1

<ipython-input-23-eb2230fe6f67>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfvegetaux['dispointerieurprot'] = dfvegetaux ['Disponibilité intérieure'] * dfvegetaux ['Ratioperproteine']

100578909.95759347

Ce qui represente en pourcentage

## Question 8

In [29]:
q_kcal = dfvegetaux["dispointerieurKcal"].sum()
q_kgprot = dfvegetaux["dispointerieurprot"].sum()
quantity = pd.DataFrame({"kcal": q_kcal, "kgprot": q_kgprot}, index=[0])

quantity

           kcal        kgprot
0  1.027916e+14  2.943865e+09

In [33]:
NB_KCAL_PER_CAPITA_PER_DAY = 2500
repQ81 = quantity["kcal"] / NB_KCAL_PER_CAPITA_PER_DAY
repQ81Pourcent = format(round(repQ81/1000000000,2))

sumkcal = quantity["kcal"].sum();
billionsDeKCalGlobla = sumkcal / 1000000000000

102.79164597666053

In [ ]:
KG_PROT_PER_CAPITA_PER_DAY = 62 * .9 * .001
repQ82 = quantity["kgprot"] / KG_PROT_PER_CAPITA_PER_DAY
repQ82Pourcent = format(round(repQ81/1000000000,2))

## question 9

In [ ]:

dispoG = dispo_alimentaire["Disponibilité de matière grasse en quantité (g/personne/jour)"].sum() + dispo_alimentaire['Disponibilité de protéines en quantité (g/personne/jour)'].sum() + (dispo_alimentaire['Disponibilité alimentaire en quantité (kg/personne/an)'].sum() * 1000) 
dispoKcal = dispo_alimentaire['Disponibilité alimentaire (Kcal/personne/jour)'].sum() * 1000000 * dispo_alimentaire["Ratioenergiepoid"]

quantityQ9 = pd.DataFrame({"kcal": dispoKcal, "kgprot": dispoG}, index=[0])


quantityQ9['kcal']

In [ ]:
NB_KCAL_PER_CAPITA_PER_DAY = 2500
repQ91 = quantityQ9["kcal"] / NB_KCAL_PER_CAPITA_PER_DAY
repQ91Pourcent = format(round(repQ91/1000000000,2))

KG_PROT_PER_CAPITA_PER_DAY = 62 * .9 * .001
repQ92 = quantityQ9["kgprot"] / KG_PROT_PER_CAPITA_PER_DAY
repQ92Pourcent = format(round(repQ92/1000000000,2))

repQ92Pourcent

## Question 10

In [ ]:
sousAlimentationCsv = pd.read_csv("../data/fr_sousalimentation.csv")
sousAlimentationCsv

In [ ]:
ssAlim = pd.read_csv("../data/fr_sousalimentation.csv")
ssAlim = ssAlim[['Code année','Code zone','Zone','Produit','Valeur','Année']]
ssAlim["Valeur"] = pd.to_numeric(ssAlim["Valeur"],errors='coerce')
ssAlim['millionPersSsAlimenter'] = ssAlim['Valeur']
ssAlim = ssAlim.loc[(ssAlim['Code année'] == 20122014 )]
ssAlim = ssAlim.groupby(['Zone']).sum()
sumSsAlim = ssAlim['millionPersSsAlimenter'].sum()
sumSsAlim

In [ ]:
sousAlimentationCsv = pd.read_csv("../data/fr_sousalimentation.csv")
sousAlimentationCsv=sousAlimentationCsv[['Code année','Code zone','Zone','Produit','Valeur','Année']]
sousAlimentationCsv["Valeur"] = pd.to_numeric(sousAlimentationCsv["Valeur"],errors='coerce')
sousAlimentationCsv['underfeed'] = sousAlimentationCsv['Valeur'] * 1000000
sousAlimentationCsv = sousAlimentationCsv.loc[(sousAlimentationCsv['Code année'] == 20122014 )]
sousAlimentationCsv = sousAlimentationCsv.groupby(['Zone']).sum()
sousAlimentationCsv

In [ ]:
sousAlimentationCsv = sousAlimentationCsv.loc[(sousAlimentationCsv['Code année'] == 20122014 )]
sousAlimentationCsv = sousAlimentationCsv.groupby(['Zone']).sum()
sousAlimentationCsv

In [ ]:
pop=pd.read_csv("../data/fr_population.csv")
pop=pop[['Zone','Valeur','Code zone']]
pop['Valeur']=pop['Valeur']*1000
pop=pop.rename(columns={"Valeur":"population", "Zone":"pays", "Code zone":"zone"})
pop

In [ ]:

##
sousAlimentationPopulation = pd.merge(left=sousAlimentationCsv, right=pop, left_on='Code zone', right_on='zone')
sousAlimentationPopulation['ProportionSsAlimentPopulation'] = (sousAlimentationPopulation['underfeed'] * 100) / sousAlimentationPopulation['population']

## moyenne Pourcentage Mondial des personne sur une année

pourcentSousAlimentationWorld = (sousAlimentationPopulation['underfeed'].sum() * 100) / sousAlimentationPopulation['population'].sum()

sousAlimentationPopulation

## Question 11

In [ ]:


## http://www.fao.org/in-action/inpho/crop-compendium/cereals-grains/fr/?page=1&ipp=7&no_cache=1&tx_dynalist_pi1[par]=YToxOntzOjE6IkwiO3M6MToiMSI7fQ==

##Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de type booléen nommée "is_cereal").

## : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), 
cerealsCsv = pd.read_csv("/Users/yassine/Desktop/data-python/fr_céréales.csv")

cerealsCsv['is_cereals'] = 'false'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Maïs', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Millet', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Blé', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Riz (Eq Blanchi)', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Orge', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Sorgho', ['is_cereals']] = 'true'
cerealsCsv = cerealsCsv.rename(columns={"Valeur":"populationSsAlimenter"})

cerealsCsv

In [ ]:
cerealsCsv = cerealsCsv[['Code zone','Zone','Unité','populationSsAlimenter','Code Produit','is_cereals']]
cerealsCsv

In [ ]:
daAnimal = dispo_alimentaire.loc[dispo_alimentaire['Origine'] == 'animale',:]
daAnimal['Aliments pour animaux'] = daAnimal['Aliments pour animaux'].astype(float)

In [ ]:
animalCereal = pd.concat([daAnimal, cerealsCsv], axis=1, join='inner')
animalCereal

In [ ]:
##En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), 
##quelle proportion (en termes de poids) est destinée à l'alimentation animale 

isCereal = animalCereal.loc[animalCereal['is_cereals'] == 'true',:]
tchekValuesAnimalCereal = isCereal.loc[isCereal['Aliments pour animaux'] > 0,:]
sumAlimentPourAnimaux = tchekValuesAnimalCereal['Aliments pour animaux'].sum()
tchekValuesAnimalCereal['ProportionFoodAnimalsByGlobalFood'] = tchekValuesAnimalCereal['Nourriture'] /  (tchekValuesAnimalCereal['Nourriture'] + tchekValuesAnimalCereal['Aliments pour animaux'])
tchekValuesAnimalCereal

In [ ]:
sumAlimentPourAnimaux

In [ ]:
sumNourritues = tchekValuesAnimalCereal['Nourriture'].sum()
globalproportionFoodAnimalsByGlobalFood = sumNourritues /  (sumAlimentPourAnimaux + sumAlimentPourAnimaux)

globalproportionFoodAnimalsByGlobalFood

In [ ]:
## Sélectionnez parmi les données des bilans alimentaires les informations .
## relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition


dispoSsAlimPop = pd.concat([dispo_alimentaire, sousAlimentationPopulation], axis=1, join='inner')

dispoSsAlimPop.columns

In [ ]:
unsetImportationNoneValues = dispoSsAlimPop.loc[dispoSsAlimPop['Importations - Quantité'] > 0,:]
unsetImportationNoneValues.sort_values('Importations - Quantité')
unsetImportationNoneValues
importations = unsetImportationNoneValues[['Code zone','Zone','Produit','Importations - Quantité']]
rankImportations = importations.sort_values(by=['Importations - Quantité'], ascending=False)[:15]
rankImportations

In [ ]:
##Parmi les données des bilans alimentaires au niveau mondial, sélectionnez 
##les 200 plus grandes importations de ces produits 
##(1 importation = une quantité d'un produit donné importée par un pays donné)

rankImportation200 = importations.sort_values(by=['Importations - Quantité'])[:200]

rankImportation200


##rep 

##imp = data[(data.item.isin(exported_products)) & (data.year == YEAR)]
##imp.sort_values("Import Quantity").iloc[200:,]

In [ ]:

pd = rankImportation200.groupby("Produit")

pd

In [ ]:
dispo_alimentaire.columns
dispo_alimentaire=dispo_alimentaire.rename(columns={"Zone":"zone"})

In [ ]:
sousAlimentationPopulation

## fin de la 11

## Question 12

In [ ]:
ratiodisp_inter = dispo_alimentaire[['produit', 'ratioDispoInterieur']].sort_values('ratioDispoInterieur', ascending=False)[:3]

ratioanim_hum = dispo_alimentaire[['produit', 'ratioAlimentPourAnimaux']].sort_values('ratioAlimentPourAnimaux', ascending=False)\[:3]

## Question 13

In [ ]:

qt_cere_pr_anim_ktonne = dispo_alimentaire.loc[
    (dispo_alimentaire.pays == "États-Unis d'Amérique")
    & (dispo_alimentaire.is_cereals == true),
    "alim_pr_anim__ktonne"
].sum()

qt_cere_pr_anim_ktonne

## question 14

In [ ]:
thailande = dispo_alimentaire.loc[
    (dispo_alimentaire'pays'] == 'Thaïlande')
    &(dispo_alimentaire['produit'] == 'Manioc'),
].iloc[0]

proportion_manioc_export = thailande['export__ktonne'] / thailande['prod__ktonne']
proportion_per_ss_alim = thailande['pop_ss_alim'] / sr['pop']