In [1]:
import pandas as pd
import numpy as np
from os import getcwd

In [2]:
pwd

'/lab/public-heath-study/data-analysis'

## Question 1
Donnez le résultat de votre calcul pour l'année 2013

In [47]:
pop=pd.read_csv("../data/fr_population.csv")
pop=pop[['Zone','Valeur','Code zone']]
pop['Valeur']=pop['Valeur']*1000
pop=pop.rename(columns={"Valeur":"population", "Zone":"pays", "Code zone":"zone"})
pop

                                       pays  population  zone
0                               Afghanistan    30552000     2
1                            Afrique du Sud    52776000   202
2                                   Albanie     3173000     3
3                                   Algérie    39208000     4
4                                 Allemagne    82727000    79
..                                      ...         ...   ...
170  Venezuela (République bolivarienne du)    30405000   236
171                                Viet Nam    91680000   237
172                                   Yémen    24407000   249
173                                  Zambie    14539000   251
174                                Zimbabwe    14150000   181

[175 rows x 3 columns]

In [4]:
pop['population'].sum()

8413993000

In [5]:
pop.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
170    False
171    False
172    False
173    False
174    False
Length: 175, dtype: bool

In [6]:
pop.drop_duplicates(subset=['pays'], keep= False)
pop=pop.loc[pop['pays']!= 'Chine',:]
pop.shape
pop['population'].sum()

6997326000

In [7]:
pop=pop.loc[pop['pays']!= 'Chine',:]

In [8]:
pop.shape

(174, 3)

In [9]:
pop['population'].sum()

6997326000

## Question 2 
Identifier les redondances

In [48]:
veg = pd.read_csv("../data/fr_vegetaux.csv")
veg

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,1173.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,-350.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,322.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104866,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
104867,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
104868,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,2013,Kcal/personne/jour,2.00,Fc,Donnée calculée
104869,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,2013,g/personne/jour,0.07,Fc,Donnée calculée
104870,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,2013,g/personne/jour,0.03,Fc,Donnée calculée

In [49]:
ani = pd.read_csv("../data/fr_animaux.csv")
ani

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37161,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5142,Nourriture,2775,Plantes Aquatiques,2013,2013,Milliers de tonnes,0.00,S,Données standardisées
37162,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,2013,kg,0.00,Fc,Donnée calculée
37163,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,0.00,Fc,Donnée calculée
37164,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
37165,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée

In [10]:
# Ajout de la variable origin
ani["Origine"] = "animale"
veg["Origine"] = "vegetale"


# On regroupe veg et ani en un unique dataframe, via une union
temp = ani.append(veg)


# Suppression de ani et veg
del ani, veg


# Transformation de temp en table pivot
data = temp.pivot_table(index=["Zone","Produit","Code Produit","Origine"],
                        columns = ["Élément"], values=["Valeur"], aggfunc=sum)

data.columns = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité alimentaire (Kcal/personne/jour)', 
                'Disponibilité alimentaire en quantité (kg/personne/an)', 
                'Disponibilité de matière grasse en quantité (g/personne/jour)', 
                'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 
                'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 
                'Semences', 'Traitement', 'Variation de stock']


dispo_alimentaire = data.reset_index()

#Nourriture = nouriture pour humain

dispo_alimentaire.head()

,Zone,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [11]:
listecolonne = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité intérieure', 
                'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 
                'Semences', 'Traitement', 'Variation de stock']


for colonne in listecolonne :
    dispo_alimentaire[colonne] = dispo_alimentaire[colonne] * 1000000

## Question 3 
Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

In [16]:
dispo_alimentaire=dispo_alimentaire.rename(columns={"Zone":"pays"})
dispo_alimentaire=dispo_alimentaire.merge(pop,on="pays")
dispo_alimentaire.head()
dispo_alimentaire['Dispokcal'] = dispo_alimentaire ['Disponibilité alimentaire (Kcal/personne/jour)']*dispo_alimentaire['population']*365
dispo_alimentaire.head()
dispo_alimentaire['Dispoperproteine']=dispo_alimentaire ['Disponibilité de protéines en quantité (g/personne/jour)']*dispo_alimentaire['population']*365/1000

dispo_alimentaire.head()

,pays,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),...,Variation de stock,population_x,zone_x,Dispokcal,Dispoperproteine,Ratioenergiepoid,population_y,zone_y,population,zone
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,...,NaN,30552000,2,5.575740e+10,8586639.6,1052.026415,30552000,2,30552000,2
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,...,NaN,30552000,2,1.115148e+10,223029.6,285.935385,30552000,2,30552000,2
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,...,NaN,30552000,2,1.115148e+10,334544.4,5575.740000,30552000,2,30552000,2
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,...,NaN,30552000,2,0.000000e+00,NaN,NaN,30552000,2,30552000,2
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,...,NaN,30552000,2,4.460592e+10,557574.0,543.974634,30552000,2,30552000,2

In [ ]:
dispo_alimentaire=dispo_alimentaire.merge(pop,on="pays")
dispo_alimentaire.head()

In [ ]:
dispo_alimentaire['Dispokcal'] = dispo_alimentaire ['Disponibilité alimentaire (Kcal/personne/jour)']*pop['population']*365
dispo_alimentaire.head()

In [ ]:
dispo_alimentaire['Dispoperproteine']=dispo_alimentaire ['Disponibilité de protéines en quantité (g/personne/jour)']*pop['population']*365/1000
dispo_alimentaire.head()

## Question 4 
Calculez pour chaque produit le ratio energie/poids

In [17]:
dispo_alimentaire['Ratioenergiepoid']= dispo_alimentaire['Dispokcal'] / dispo_alimentaire ['Nourriture']
dispo_alimentaire['Ratioperproteine']= dispo_alimentaire['Dispoperproteine']/ dispo_alimentaire ['Nourriture']
dispo_alimentaire.head()
dispo_alimentaire = dispo_alimentaire.replace([np.inf, -np.inf],np.nan)
ratio =dispo_alimentaire.groupby ('Produit').mean()
ratio =ratio.reset_index()
ratio.head()
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Oeufs',:]
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Avoine',:]

  Produit  Ratioenergiepoid  Ratioperproteine
7  Avoine       1892.485132          0.081775

In [ ]:
dispo_alimentaire = dispo_alimentaire.replace([np.inf, -np.inf],np.nan)
ratio =dispo_alimentaire.groupby ('Produit').mean()
ratio =ratio.reset_index()
ratio.head()

In [ ]:
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Oeufs',:]

la teneur en proteine de l'avoine

In [ ]:
ratio =ratio[['Produit', 'Ratioenergiepoid', 'Ratioperproteine']]
ratio.loc[ratio['Produit'] == 'Avoine',:]

## Question 5
Citez 5 aliments parmi les 20 aliments les plus caloriques

In [ ]:
ratio.sort_values (by = 'Ratioenergiepoid', ascending = False)

## Question 6
Calculez pour les produits végétaux la dispo interieur mondiale exprimé en kcal

In [ ]:
dfvegetaux = dispo_alimentaire.loc[dispo_alimentaire['Origine'] == 'vegetale',:]
dfvegetaux.head()

In [ ]:
dfvegetaux['dispointerieurKcal'] = dfvegetaux ['Disponibilité intérieure'] * dfvegetaux['Ratioenergiepoid']
dfvegetaux.head()

## Question 7
Combien d'humains pourraient être nourris si toute la disponibilité intérieur mondiale de produits végétaux était utilisé pour de la nourriture

En termes de calories sachant qu'en moyenne une personne a besoin de 2500 calories par jour

In [ ]:
resp1 = dfvegetaux['dispointerieurKcal'].sum()/ 365 / 2500
KG_PROT_PER_CAPITA_PER_DAY = 62 * .9 * .001
dfvegetaux['dispointerieurprot'] = dfvegetaux ['Disponibilité intérieure'] * dfvegetaux ['Ratioperproteine']
dfvegetaux.head()
resp2 = dfvegetaux['dispointerieurprot'].sum()/KG_PROT_PER_CAPITA_PER_DAY
resp1

milliardDepersonneFood = format(round(repQ81/1000000000,2))

Ce qui represente en pourcentage

## Question 8

In [ ]:
q_kcal = dfvegetaux["dispointerieurKcal"].sum()
q_kgprot = dfvegetaux["dispointerieurprot"].sum()
quantity = pd.DataFrame({"kcal": q_kcal, "kgprot": q_kgprot}, index=[0])

quantity

In [ ]:
NB_KCAL_PER_CAPITA_PER_DAY = 2500
repQ81 = quantity["kcal"] / NB_KCAL_PER_CAPITA_PER_DAY
repQ81Pourcent = format(round(repQ81/1000000000,2))

sumkcal = quantity["kcal"].sum();
billionsDeKCalGlobla = sumkcal / 1000000000000

In [ ]:
KG_PROT_PER_CAPITA_PER_DAY = 62 * .9 * .001
repQ82 = quantity["kgprot"] / KG_PROT_PER_CAPITA_PER_DAY
repQ82Pourcent = format(round(repQ81/1000000000,2))

## question 9

In [ ]:

dispoG = dispo_alimentaire["Disponibilité de matière grasse en quantité (g/personne/jour)"].sum() + dispo_alimentaire['Disponibilité de protéines en quantité (g/personne/jour)'].sum() + (dispo_alimentaire['Disponibilité alimentaire en quantité (kg/personne/an)'].sum() * 1000) 
dispoKcal = dispo_alimentaire['Disponibilité alimentaire (Kcal/personne/jour)'].sum() * 1000000 * dispo_alimentaire["Ratioenergiepoid"]

quantityQ9 = pd.DataFrame({"kcal": dispoKcal, "kgprot": dispoG}, index=[0])


quantityQ9['kcal']

In [ ]:
NB_KCAL_PER_CAPITA_PER_DAY = 2500
repQ91 = quantityQ9["kcal"] / NB_KCAL_PER_CAPITA_PER_DAY
repQ91Pourcent = format(round(repQ91/1000000000,2))

KG_PROT_PER_CAPITA_PER_DAY = 62 * .9 * .001
repQ92 = quantityQ9["kgprot"] / KG_PROT_PER_CAPITA_PER_DAY
repQ92Pourcent = format(round(repQ92/1000000000,2))

repQ91Pourcent

## Question 10

In [50]:
sousAlimentationCsv = pd.read_csv("../data/fr_sousalimentation.csv")
sousAlimentationCsv

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,6.6,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN
1017,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,7.8,F,Estimation FAO,NaN
1018,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,8.2,F,Estimation FAO,NaN
1019,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,8.5,F,Estimation FAO,NaN

In [ ]:
ssAlim = pd.read_csv("../data/fr_sousalimentation.csv")
ssAlim = ssAlim[['Code année','Code zone','Zone','Produit','Valeur','Année']]
ssAlim["Valeur"] = pd.to_numeric(ssAlim["Valeur"],errors='coerce')
ssAlim['millionPersSsAlimenter'] = ssAlim['Valeur']
ssAlim = ssAlim.loc[(ssAlim['Code année'] == 20122014 )]
ssAlim = ssAlim.groupby(['Zone']).sum()
sumSsAlim = ssAlim['millionPersSsAlimenter'].sum()
sumSsAlim

In [ ]:
sousAlimentationCsv = pd.read_csv("../data/fr_sousalimentation.csv")
sousAlimentationCsv=sousAlimentationCsv[['Code année','Code zone','Zone','Produit','Valeur','Année']]
sousAlimentationCsv["Valeur"] = pd.to_numeric(sousAlimentationCsv["Valeur"],errors='coerce')
sousAlimentationCsv['underfeed'] = sousAlimentationCsv['Valeur'] * 1000000
sousAlimentationCsv = sousAlimentationCsv.loc[(sousAlimentationCsv['Code année'] == 20122014 )]
sousAlimentationCsv = sousAlimentationCsv.groupby(['Zone']).sum()
sousAlimentationCsv

In [ ]:
sousAlimentationCsv = sousAlimentationCsv.loc[(sousAlimentationCsv['Code année'] == 20122014 )]
sousAlimentationCsv = sousAlimentationCsv.groupby(['Zone']).sum()
sousAlimentationCsv

In [ ]:
pop=pd.read_csv("../data/fr_population.csv")
pop=pop[['Zone','Valeur','Code zone']]
pop['Valeur']=pop['Valeur']*1000
pop=pop.rename(columns={"Valeur":"population", "Zone":"pays", "Code zone":"zone"})
pop

In [ ]:

##
sousAlimentationPopulation = pd.merge(left=sousAlimentationCsv, right=pop, left_on='Code zone', right_on='zone')
sousAlimentationPopulation['ProportionSsAlimentPopulation'] = (sousAlimentationPopulation['underfeed'] * 100) / sousAlimentationPopulation['population']

## moyenne Pourcentage Mondial des personne sur une année

pourcentSousAlimentationWorld = (sousAlimentationPopulation['underfeed'].sum() * 100) / sousAlimentationPopulation['population'].sum()

sousAlimentationPopulation

## Question 11

In [ ]:


## http://www.fao.org/in-action/inpho/crop-compendium/cereals-grains/fr/?page=1&ipp=7&no_cache=1&tx_dynalist_pi1[par]=YToxOntzOjE6IkwiO3M6MToiMSI7fQ==

##Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de type booléen nommée "is_cereal").

## : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), 
cerealsCsv = pd.read_csv("/Users/yassine/Desktop/data-python/fr_céréales.csv")

cerealsCsv['is_cereals'] = 'false'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Maïs', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Millet', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Blé', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Riz (Eq Blanchi)', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Orge', ['is_cereals']] = 'true'
cerealsCsv.loc[cerealsCsv['Produit'] == 'Sorgho', ['is_cereals']] = 'true'
cerealsCsv = cerealsCsv.rename(columns={"Valeur":"populationSsAlimenter"})

cerealsCsv

In [ ]:
cerealsCsv = cerealsCsv[['Code zone','Zone','Unité','populationSsAlimenter','Code Produit','is_cereals']]
cerealsCsv

In [ ]:
daAnimal = dispo_alimentaire.loc[dispo_alimentaire['Origine'] == 'animale',:]
daAnimal['Aliments pour animaux'] = daAnimal['Aliments pour animaux'].astype(float)

In [51]:
animalCereal = pd.concat([daAnimal, cerealsCsv], axis=1, join='inner')
animalCereal

NameError: name 'daAnimal' is not defined

In [ ]:
##En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), 
##quelle proportion (en termes de poids) est destinée à l'alimentation animale 

isCereal = animalCereal.loc[animalCereal['is_cereals'] == 'true',:]
tchekValuesAnimalCereal = isCereal.loc[isCereal['Aliments pour animaux'] > 0,:]
sumAlimentPourAnimaux = tchekValuesAnimalCereal['Aliments pour animaux'].sum()
tchekValuesAnimalCereal['ProportionFoodAnimalsByGlobalFood'] = tchekValuesAnimalCereal['Nourriture'] /  (tchekValuesAnimalCereal['Nourriture'] + tchekValuesAnimalCereal['Aliments pour animaux'])
tchekValuesAnimalCereal

In [ ]:
sumAlimentPourAnimaux

In [ ]:
sumNourritues = tchekValuesAnimalCereal['Nourriture'].sum()
globalproportionFoodAnimalsByGlobalFood = sumNourritues /  (sumAlimentPourAnimaux + sumAlimentPourAnimaux)

globalproportionFoodAnimalsByGlobalFood

In [ ]:
## Sélectionnez parmi les données des bilans alimentaires les informations .
## relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition


dispoSsAlimPop = pd.concat([dispo_alimentaire, sousAlimentationPopulation], axis=1, join='inner')

dispoSsAlimPop.columns

In [ ]:
unsetImportationNoneValues = dispoSsAlimPop.loc[dispoSsAlimPop['Importations - Quantité'] > 0,:]
unsetImportationNoneValues.sort_values('Importations - Quantité')
unsetImportationNoneValues
importations = unsetImportationNoneValues[['Code zone','Zone','Produit','Importations - Quantité']]
rankImportations = importations.sort_values(by=['Importations - Quantité'], ascending=False)[:15]
rankImportations

In [ ]:
##Parmi les données des bilans alimentaires au niveau mondial, sélectionnez 
##les 200 plus grandes importations de ces produits 
##(1 importation = une quantité d'un produit donné importée par un pays donné)

rankImportation200 = importations.sort_values(by=['Importations - Quantité'])[:200]

rankImportation200


##rep 

##imp = data[(data.item.isin(exported_products)) & (data.year == YEAR)]
##imp.sort_values("Import Quantity").iloc[200:,]

In [ ]:

pd = rankImportation200.groupby("Produit")

pd

In [ ]:
dispo_alimentaire.columns
dispo_alimentaire=dispo_alimentaire.rename(columns={"Zone":"zone"})

In [ ]:
sousAlimentationPopulation

## fin de la 11

## Question 12

In [ ]:
ratiodisp_inter = dispo_alimentaire[['produit', 'ratioDispoInterieur']].sort_values('ratioDispoInterieur', ascending=False)[:3]

ratioanim_hum = dispo_alimentaire[['produit', 'ratioAlimentPourAnimaux']].sort_values('ratioAlimentPourAnimaux', ascending=False)\[:3]

## Question 13

In [ ]:

qt_cere_pr_anim_ktonne = dispo_alimentaire.loc[
    (dispo_alimentaire.pays == "États-Unis d'Amérique")
    & (dispo_alimentaire.is_cereals == true),
    "alim_pr_anim__ktonne"
].sum()

qt_cere_pr_anim_ktonne

## question 14

In [ ]:
thailande = dispo_alimentaire.loc[
    (dispo_alimentaire'pays'] == 'Thaïlande')
    &(dispo_alimentaire['produit'] == 'Manioc'),
].iloc[0]

proportion_manioc_export = thailande['export__ktonne'] / thailande['prod__ktonne']
proportion_per_ss_alim = thailande['pop_ss_alim'] / sr['pop']

## Calculer le nombre de personne qui serais nourris avec toute la disponibilté alimentaire

In [39]:
##calcule dispointerieurKcal =  (dispoKalorie / nourriture ) 
## somme de toute les calories 
resp1 = dfvegetaux['dispointerieurKcal'].sum() / 365 / 2500
milliardDepersonneFood = format(round(resp1/1000000000,2))

milliardDepersonneFood
milliardDepersonneFood = pd.to_numeric(milliardDepersonneFood, downcast='float')
milliardDepersonneFood

13.49

In [ ]:
dispoAlimentaireMondial

In [40]:
sumPop = pop['population'].sum()
millardPop  = format(round(sumPop/1000000000,2))
millardPop = pd.to_numeric(millardPop, downcast='float')
millardPop

7.0

In [46]:

raisePopVegetauxFood = (milliardDepersonneFood - millardPop) / milliardDepersonneFood * 100

raisePopVegetauxFood

48.10971021652222

In [ ]:
cereals = pd.read_csv("../data/fr_cereales.csv")
cereals